# Generated by Django 4.2 on 2023-05-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieTriggerApp', '0002_list_type_alter_list_description_remove_list_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trigger',
            field=models.ManyToManyField(to='MovieTriggerApp.trigger'),
        ),
    ]
