# Generated by Django 4.2 on 2023-04-09 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieTriggerApp', '0002_remove_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MovieTriggerApp.movie'),
        ),
        migrations.AlterField(
            model_name='list',
            name='viewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MovieTriggerApp.viewer'),
        ),
    ]
