# Generated by Django 4.2 on 2023-04-09 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieTriggerApp', '0003_alter_list_movie_alter_list_viewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MovieTriggerApp.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trigger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MovieTriggerApp.trigger'),
        ),
    ]
