# Generated by Django 4.2 on 2023-04-10 21:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieTriggerApp', '0004_alter_movie_genre_alter_movie_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='Viewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MovieTriggerApp.viewer'),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MovieTriggerApp.movie'),
        ),
    ]
