# Generated by Django 4.2 on 2023-05-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieTriggerApp', '0004_alter_trigger_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='movie',
            field=models.ManyToManyField(related_name='movie', to='MovieTriggerApp.movie'),
        ),
    ]
