# Generated by Django 4.2 on 2023-04-09 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieTriggerApp', '0004_alter_movie_genre_alter_movie_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Viewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MovieTriggerApp.viewer'),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MovieTriggerApp.movie'),
        ),
    ]
