# Generated by Django 4.2 on 2023-04-10 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieTriggerApp', '0005_review_description_review_rating_alter_review_viewer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MovieTriggerApp.review'),
        ),
    ]
