# Generated by Django 4.2 on 2023-05-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieTriggerApp', '0008_alter_genre_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trigger',
            field=models.ManyToManyField(related_name='triggers', to='MovieTriggerApp.trigger'),
        ),
    ]
