# Generated by Django 4.2 on 2023-05-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieTriggerApp', '0010_alter_genre_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(choices=[('A', 'Action'), ('C', 'Comedy'), ('D', 'Drama'), ('F', 'Fantasy'), ('H', 'Horror'), ('M', 'Mystery'), ('R', 'Romance')], default='D', max_length=255, unique=True),
        ),
    ]
