# Generated by Django 4.2.1 on 2023-05-15 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieTriggerApp', '0015_alter_viewer_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewer',
            name='email',
        ),
    ]
